### PR TITLE
feat: incremental annotation processor

### PR DESCRIPTION
**Pull request by FunkyMuse**

### CODE REVIEW

**Comment by FunkyMuse** [comment]
updated the gradle file as well for android studio 4.1

**Comment by LanderlYoung** [comment]
Thanks for this PR!

Looks added meta-data for gradle incremental annotation process.

However, in this doc https://docs.gradle.org/5.0/userguide/java_plugin.html#sec:incremental_annotation_processing it says

1. They must generate their files using the Filer API. 
3. If they use Filer#createResource, Gradle will recompile all source files. See gradle/issues/4702


If `jenny.outputDirectory` is not passed, Jenny will use the Filer#createResource API, which according to the rule it won't be incremental.
Also, If `jenny.outputDirectory` is not passed, Jenny will not use the Filer API, which disobeys the first rule.

I'm thinking if this could be a problem.

**Comment by FunkyMuse** [comment]
> Thanks for this PR!
> 
> Looks added meta-data for gradle incremental annotation process.
> 
> However, in this doc https://docs.gradle.org/5.0/userguide/java_plugin.html#sec:incremental_annotation_processing it says
> 
>     1. They must generate their files using the Filer API.
> 
>     2. If they use Filer#createResource, Gradle will recompile all source files. See gradle/issues/4702
> 
> 
> If `jenny.outputDirectory` is not passed, Jenny will use the Filer#createResource API, which according to the rule it won't be incremental.
> Also, If `jenny.outputDirectory` is not passed, Jenny will not use the Filer API, which disobeys the first rule.
> 
> I'm thinking if this could be a problem.

https://github.com/CraZyLegenD/FreshAdapter

You can check out my implementation it works perfectly without recompilation

**Comment by FunkyMuse** [comment]
But my thinking is that this repo is gonna fall under isolating instead of aggregating

**Comment by LanderlYoung** [comment]
Thanks! I'll try it.

> But my thinking is that this repo is gonna fall under isolating instead of aggregating

Yes, it should, but there is a "jenny_fusion_proxies.h" file that needs to be worked in the aggregate mode. Just because we need to know all the proxy files.

**Comment by FunkyMuse** [comment]
> Thanks! I'll try it.
> 
> > But my thinking is that this repo is gonna fall under isolating instead of aggregating
> 
> Yes, it should, but there is a "jenny_fusion_proxies.h" file that needs to be worked in the aggregate mode. Just because we need to know all the proxy files.

I tested the pull request with isolating and it recompiles everything, with aggregating as it currently is it doesn't.
Of course there are corner cases when recompilation happens and that's usually when static member variable is changed or package moved etc... which are not under your control.

**Comment by LanderlYoung** [comment]
>  I tested the pull request with isolating and it recompiles everything, with aggregating as it currently is it doesn't.

Yes, I tested it as well, and the compiler says:

> Full recompilation is required because the generated resource 'jenny/proxy/jnihelper.h in SOURCE_OUTPUT' must have exactly one originating element, but had 0. Analysis took 0.0 secs.

So not only does `jenny_fusion_header.h` blocks the way, so does the `jnihelper.h` too.

Now as I tested `aggregating` mode works pretty well! Gradle is smart enough to figure which files were used to the annotation processor and if any of them is changed, all of them will be recompiled, but still, It's an incremental compilation (not all code are recompiled)

Great work! Thanks, man!

And also, sorry for my being busy these days.

**Pull request merged**
